# Input protein fasta file (.faa)

input_file: "/hps/research/finn/aalmeida/projects/latinbiota/prokaryotes/oscillospirales/mmseqs2/mmseqs_cluster_rep_nosingle.fa"

# Directory containing eggNOG, dbCAN2 and KOFam DBs

db_dir: "/hps/research/finn/aalmeida/data/databases"

# Output directory

output_dir: "/hps/research/finn/aalmeida/projects/latinbiota/prokaryotes/oscillospirales/mmseqs2/annotation"

# Number of files to split input proteins

nsplits: 1000

# Number of cores

ncores: 4
